sudo: false

language: python

matrix:
  include:
    # OSX doesn't work with `language: python` yet
    - os: osx
      language: generic
    #- os: linux
    #  python: 2.6
    #- os: linux
    #  python: 2.7
    #- os: linux
    #  python: 3.4
    #- os: linux
    #  python: 3.5
    #- os: linux
    #  python: pypy

addons:
  apt:
    packages:
      - libenchant-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf ./enchant; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv ./venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./venv/bin/activate; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install https://pypi.python.org/packages/37/de/cb37af61ac1473ed9c50ee57327f84425d7f697d58c0750526e73f4831f8/pyenchant-1.6.10-py2.py3.cp27.cp32.cp33.cp34.cp35.pp27.pp33-none-macosx_10_6_intel.macosx_10_9_intel.whl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install https://rfk.id.au/static/scratch/pyenchant-1.6.10-py2.py3.cp27.cp32.cp33.cp34.cp35.pp27.pp33-none-any.whl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -c "import enchant; enchant._runtestsuite()"; fi

script:
  - true

notifications:
  - email: ryan@rfk.id.au
